[workspace]
resolver = "2"
members = [
    "minitrace",
]

[profile.dev]
opt-level = 0
debug = 0
codegen-units = 4
lto = false
incremental = true
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = true
codegen-units = 1
lto = true
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false
